### PR TITLE
Get the CPU information from lscpu

### LINKED ISSUE #136: Update to retrieve CPU information using lscpu
As noted in #135 it will be more robust to get CPU/socket/thread/core counts from `lscpu` as it is tested on many more architectures than we have available (use `prmon::cmd_pipe_output` to run the external command). The current implementation crashes on ARM machines.

### PR DESCRIPTION
**Pull request by amete**
As we discussed in #135 using `lscpu` instead of manually reading/parsing `/proc/cpuinfo` is more robust against various architectures (especially non-x86). This is especially easy now given that we have `prmon::cmd_pipe_output` to invoke any command. On my laptop, the output looks like this now:

```
{
  ...  
  "HW": {
    "cpu": {
      "Core(s) per socket": 1,
      "Model name": "Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz",
      "Socket(s)": 4,
      "Thread(s) per core": 1
    },  
    "mem": {
      "MemTotal": 2038904
    }   
  },  
  ...
}
```

Closes #136.

### CODE REVIEW

File: package/src/cpumon.cpp [hunk 1]
```diff
@@ -63,60 +63,57 @@ std::map<std::string, double> const cpumon::get_json_average_stats(
...
+              << cmd_result.first << ")" << std::endl;
     return;
   }
 
-  // Metrics to read from the input
-  std::vector<std::string> metrics{"processor", "model name", "siblings",
-                                   "cpu cores"};
-  unsigned int nCPU = 0, nSiblings = 0, nCores = 0;
+  // Metrics that'll be kept from the lscpu output
+  const std::vector<std::string> metrics{
```
Comment (graeme-a-stewart) [inline package/src/cpumon.cpp:79]: We should add the total number of CPUs as well (`CPU(s)`)

File: package/src/cpumon.cpp [hunk 2]
```diff
@@ -63,60 +63,57 @@ std::map<std::string, double> const cpumon::get_json_average_stats(
...
+
+    // Read "key":"value" pairs
+    key = line.substr(0, splitIdx);
+    value = line.substr(splitIdx + 1);
+    if (key.empty() || value.empty()) continue;
+    key = std::regex_replace(key, std::regex("^\\s+|\\s+$"), "");
+    value = std::regex_replace(value, std::regex("^\\s+|\\s+$"), "");
+
+    // Fill the JSON with the information
+    for (const auto& metric : metrics) {
```
Comment (graeme-a-stewart) [inline package/src/cpumon.cpp:109]: This is quadratic in complexity, but given that the output is small and the metrics are small in number I think we can get away with it (also, it's only called once)

**Comment by graeme-a-stewart** [comment]
@amete, thanks a lot.

The only additional comment I have is that the key names produced by `lscpu` are quite ugly - they have spaces and parentheses in them. I would be inclined to simplify them to:

```
CPUs
Sockets
CoresPerSocket
ThreadsPerCore
```

That makes them easier for a client to handle. I am aware that this is a small extra level of complexity (I'd suggest a `map(lscpu key -> our key)`), but I think it's nicer.

What do you think?

**Comment by amete** [comment]
I agree @graeme-a-stewart, we can easily map the names as you suggested.

**Comment by graeme-a-stewart** [comment]
Also, on my Pi4 I get:

```
    "cpu": {
      "Core(s) per socket": 4,
      "Model name": "Cortex-A72",
      "Socket(s)": 1,
      "Thread(s) per core": 1
    },
```

Which is exactly what we wanted.

File: package/src/cpumon.cpp (hunk 2 above)
Comment (amete) [reply package/src/cpumon.cpp:109]: That was my line of thinking as well. However, given that we have only a handful of variables (conditions), I can just as well put in an if statement here. What do you think?

File: package/src/cpumon.cpp (hunk 1 above)
Comment (amete) [reply package/src/cpumon.cpp]: Done.

File: package/src/cpumon.cpp (hunk 2 above)
Comment (amete) [reply package/src/cpumon.cpp]: I switched to using a simple `if` here.

**Comment by amete** [comment]
I just pushed a new version @graeme-a-stewart, let me know what you think, many thanks 😄

**Comment by amete** [comment]
BTW, this is how this block looks now:

```
   "cpu": {
      "CPUs": 4,
      "CoresPerSocket": 1,
      "ModelName": "Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz",
      "Sockets": 4,
      "ThreadsPerCore": 1
    },
```

**Comment by amete** [comment]
Another BTW, running within an Ubuntu based container on my MacBook Pro seems to have incorrect `/proc/cpuinfo` about the hardware. I have a single quad-core Intel i5 but `/proc/cpuinfo` publishes this as four single-core processors. That's interesting.

**Comment by graeme-a-stewart** [comment]
> BTW, this is how this block looks now:
> 
> ```
>    "cpu": {
>       "CPUs": 4,
>       "CoresPerSocket": 1,
>       "ModelName": "Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz",
>       "Sockets": 4,
>       "ThreadsPerCore": 1
>     },
> ```

Wait... that can't be correct. How can you have a 4 socket machine in your laptop?

Doing a few checks on my platforms

**Comment by graeme-a-stewart** [comment]
OK... I think it's actually an issue with Docker on OS X. The VM layer is translating each CPU that is given to Docker as a separate socket. For both bare metal and Docker on Linux I get what I expect:

```
    "cpu": {
      "CPUs": 16,
      "CoresPerSocket": 8,
      "ModelName": "Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz",
      "Sockets": 1,
      "ThreadsPerCore": 2
    },
```

And it's fine on the Pi too:

```
    "cpu": {
      "CPUs": 4,
      "CoresPerSocket": 4,
      "ModelName": "Cortex-A72",
      "Sockets": 1,
      "ThreadsPerCore": 1
    },
```

In fact the older version of the parser, directly from `/proc/cpuinfo` also reports the same when run on OS X Docker.

So it's not at all a problem we need to worry about in practice.

File: package/src/cpumon.cpp [hunk 3]
```diff
@@ -106,12 +110,12 @@ void const cpumon::get_hardware_info(nlohmann::json& hw_json) {
     value = std::regex_replace(value, std::regex("^\\s+|\\s+$"), "");
 
     // Fill the JSON with the information
-    for (const auto& metric : metrics) {
-      if (key.compare(metric) != 0) continue;
+    if (key == "Model name" || key == "CPU(s)" || key == "Socket(s)" ||
```
Comment (graeme-a-stewart) [inline package/src/cpumon.cpp:113]: Oh no... I actually much preferred the previous version. Now you have these key names encoded twice, *in different places*, which is bad.

I actually doubt that it's any more efficient than the previous `for`loop (which can be slightly improved by adding a `break` after you process the match, because each key can only match once).

Comment (amete) [reply package/src/cpumon.cpp]: No problem, let me know how it looks now 👍

File: package/src/cpumon.cpp [hunk 4]
```diff
@@ -63,60 +63,62 @@ std::map<std::string, double> const cpumon::get_json_average_stats(
...
+
+    // Read "key":"value" pairs
+    key = line.substr(0, splitIdx);
+    value = line.substr(splitIdx + 1);
+    if (key.empty() || value.empty()) continue;
+    key = std::regex_replace(key, std::regex("^\\s+|\\s+$"), "");
+    value = std::regex_replace(value, std::regex("^\\s+|\\s+$"), "");
+
+    // Fill the JSON with the information
+    for (const auto& metric : metricToName) {
```
Comment (graeme-a-stewart) [inline package/src/cpumon.cpp:113]: Oh but wait... now we can use the map:

```cpp
if (metricToName.count(metric) == 1) {
...
}
```

That's the right way to do it!

Comment (amete) [reply package/src/cpumon.cpp]: Good point, changed now. I seldom use maps, as a deliberate choice, so this completely escaped me. Is this still an `O(N)` operation or is it actually smarter than that?

Comment (amete) [reply package/src/cpumon.cpp]: Wait I got it wrong 😄

Comment (amete) [reply package/src/cpumon.cpp]: OK, we should be good now, today is not my day I guess.

File: package/src/cpumon.cpp [hunk 5]
```diff
@@ -63,60 +63,60 @@ std::map<std::string, double> const cpumon::get_json_average_stats(
...
-  // Metrics to read from the input
-  std::vector<std::string> metrics{"processor", "model name", "siblings",
-                                   "cpu cores"};
-  unsigned int nCPU = 0, nSiblings = 0, nCores = 0;
-
-  // Loop over the file
-  std::string line;
-  while (std::getline(cpuInfoFile, line)) {
+  // Map lscpu names to the desired ones in the JSON
+  const std::map<std::string, std::string> metricToName{
```
Comment (graeme-a-stewart) [inline package/src/cpumon.cpp:79]: Although it's not a big deal, make this an `unordered_map`... (just good practice)

File: package/src/cpumon.cpp [hunk 6]
```diff
@@ -63,60 +63,60 @@ std::map<std::string, double> const cpumon::get_json_average_stats(
...
+    key = line.substr(0, splitIdx);
+    value = line.substr(splitIdx + 1);
+    if (key.empty() || value.empty()) continue;
+    key = std::regex_replace(key, std::regex("^\\s+|\\s+$"), "");
+    value = std::regex_replace(value, std::regex("^\\s+|\\s+$"), "");
+
+    // Fill the JSON with the information
+    if (metricToName.count(key) == 1) {
+      if (isNumber(value))
+        hw_json["HW"]["cpu"][metricToName.at(key)] = std::stoi(value);
```
Comment (graeme-a-stewart) [inline package/src/cpumon.cpp:115]: Isn't `metricToName[key]` better? Although `at` gives a bounds check, we know already that the key is present. And if it weren't then it would throw `std::out_of_range` that we don't catch and the program would crash anyway, so it's no protection.

File: package/src/cpumon.cpp (hunk 4 above)
Comment (graeme-a-stewart) [reply package/src/cpumon.cpp]: I think we are both ready for the weekend!

Comment (graeme-a-stewart) [reply package/src/cpumon.cpp]: > Good point, changed now. I seldom use maps, as a deliberate choice, so this completely escaped me. Is this still an `O(N)` operation or is it actually smarter than that?

As it's a map (with a hash) it's usually constant (with the worst case being linear).

Comment (graeme-a-stewart) [reply package/src/cpumon.cpp]: The main advantage here of using a map is it makes the program's intention clearer than looping over a vector, which means less chance of screwing up... 😁

File: package/src/cpumon.cpp (hunk 6 above)
Comment (amete) [reply package/src/cpumon.cpp:115]: operator `[]` is not declared as const for `std::map` (or `std::unordered_map` for that matter), so that gives me a compilation error since the method is `cont`. That's why I ended up using `at`:

```
/home/amete/github/prmon/package/src/cpumon.cpp: In member function 'virtual const void cpumon::get_hardware_info(nlohmann::json&)':
/home/amete/github/prmon/package/src/cpumon.cpp:117:46: error: passing 'const std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >' as 'this' argument discards qualifiers [-fpermissive]
  117 |         hw_json["HW"]["cpu"][metricToName[key]] = value;
```

Let me know if I'm missing something here.

Comment (graeme-a-stewart) [reply package/src/cpumon.cpp:115]: You are right - I missed that! `[]` is also used a setter so it's not `const`. Yes, just leave it as is. Sorry for the noise!

File: package/src/cpumon.cpp (hunk 5 above)
Comment (amete) [reply package/src/cpumon.cpp]: Done.

File: package/src/cpumon.cpp (hunk 3 above)
Comment (amete) [reply package/src/cpumon.cpp]: We re-wrote this bit, so I'm resolving.

**Comment by amete** [comment]
Let me know how it all looks now @graeme-a-stewart, many thanks 👍

**Comment by graeme-a-stewart** [comment]
Thanks a lot! All LGTM 👍
